my_list=[]
print("Before appending:", my_list)
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print("After appending:", my_list)
my_list.insert(1,15)
my_list.extend([50,60,70])
print("After insert & extend:",my_list)
del my_list[7]
print(my_list)
my_list.sort()
print("After sort:", my_list)
index_30 = my_list.index(30)
print("The index of the value 30 in my_list:",index_30)
